SELECT * WHERE {

    <RESULT_SET>

    ?id a skos:Concept .

    OPTIONAL {
        ?id skos:prefLabel ?nazev .
        FILTER(lang(?nazev)=?lang)
    }

    OPTIONAL {
        ?id skos:definition ?definice .
        FILTER(lang(?definice)=?lang)
    }

    OPTIONAL {
        ?id rdfs:subClassOf ?nadtyp__id .
        OPTIONAL {
            ?nadtyp__id skos:prefLabel ?nadtyp__nazev .
            FILTER(lang(?nadtyp__nazev) = ?lang)
        }
        FILTER(?nadtyp__id not in (skos:Concept,owl:Class,owl:NamedIndividual,owl:ObjectProperty,owl:DatatypeProperty,owl:AnnotationProperty))
        FILTER(isIri(?nadtyp__id))
    }

    OPTIONAL {
        ?id a ?typ__id .
        OPTIONAL {
            ?typ__id skos:prefLabel ?typ__nazev .
            FILTER(lang(?typ__nazev) = ?lang)
        }
        FILTER(?typ__id not in (skos:Concept,owl:Class,owl:NamedIndividual,owl:ObjectProperty,owl:DatatypeProperty,owl:AnnotationProperty))
        FILTER(isIri(?nadtyp__id))
    }

        # UNCOMMENT FOR COMPACT
        #        '  OPTIONAL { ?typvlastnosti__id ((rdfs:domain|(rdfs:domain/(owl:unionOf/rdf:rest*/rdf:first)?))) ?id . '
        #        '          ?typvlastnosti__id skos:prefLabel ?typvlastnosti__nazev ; a zs:typ-vlastnosti .}'
        #        '  OPTIONAL { ?typvztahu__id ((rdfs:domain|(rdfs:domain/(owl:unionOf/rdf:rest*/rdf:first)?))) ?id . '
        #        '          ?typvztahu__id skos:prefLabel ?typvztahu__nazev ; a zs:typ-vztahu .}'
        # UNCOMMENT FOR COMPACT

    # UNCOMMENT FOR FULL
    OPTIONAL { ?typvlastnosti__id rdfs:subClassOf ?r2 .
        ?r2 owl:onProperty zs:je-vlastností . ?typvlastnosti__id a zs:typ-vlastnosti .
        ?r2 (owl:allValuesFrom/(owl:unionOf/rdf:rest*/rdf:first)?) ?id .
        OPTIONAL {
            ?typvlastnosti__id skos:prefLabel ?typvlastnosti__nazev .
            FILTER(lang(?typvlastnosti__nazev) = ?lang )
        }
    }

    OPTIONAL { ?typvztahu__id rdfs:subClassOf ?r1.
        ?r1 owl:onProperty zs:má-vztažený-prvek-1 . ?typvztahu__id a zs:typ-vztahu .
        ?r1 (owl:allValuesFrom/(owl:unionOf/rdf:rest*/rdf:first)?) ?id .
        OPTIONAL {
            ?typvztahu__id skos:prefLabel ?typvztahu__nazev .
            FILTER(lang(?typvztahu__nazev) = ?lang )
        }
    }
    # END UNCOMMENT

    OPTIONAL {
        ?id skos:inScheme ?glosar__id .
        OPTIONAL {
            ?glosar__id rdfs:label ?glosar__nazev .
            FILTER(lang(?glosar__nazev) = ?lang)
        }
    }
}